README.md
ardupilot_gz_bringup/config/iris.rviz
ardupilot_gz_bringup/config/iris_bridge.yaml
ardupilot_gz_bringup/launch/bringup_iris.launch.py
ardupilot_gz_bringup/launch/iris.launch.py
ardupilot_gz_gazebo/worlds/iris.sdf
ros2_gz.repos

Update launch files to use the version of the Iris with the camera and gimbal.
- https://github.com/ArduPilot/ROS2_Tools/issues/2
- Use modified versions of the `ardupilot_gazebo` models using `package://` URI's rather than the `model://` versions.
- Update the bridge yaml to map the camera stream to ROS 2.
- Update `rviz` config to display the image.
- Update the launch files to use the parameters for the gimbal variant of the iris.
- Update the launch files to  set the `SDF_PATH` correctly for `sdformat_urdf`.
- Add the gimbal to the iris world file.
- Add a `ros2_gz.repos` file detailing all source dependencies.
Figure: iris with gimbal and camera in Gazebo streaming sensor data to ROS 2.

Copter: add gimbal and camera to iris

---

README.md
ardupilot_gz_bringup/launch/robots/iris.launch.py
ardupilot_gz_description/models/README.md

Incorporate launch file changes in upstream packages.
- Launch files moved from `ardupilot_dds_tests` to `ardupilit_sitl`.
- `bringup_sitl_dds.launch.py` renamed to `sitl_dds.launch.py`.
- Update docs.

Tools: upstream changes to ardupilot_sitl

---

ardupilot_gz_bringup/config/iris_bridge.yaml
ardupilot_gz_gazebo/worlds/iris_runway.sdf

Add simple battery model and additional sensors to the Iris.
- Add battery plugin.
- Add air_pressure
- Add magnetometer
- Add navsat
Example showing battery message mapped from Gazebo through to ROS 2.
```bash
$ ros2 topic echo /battery
---
header:
stamp:
sec: 222
nanosec: 324000000
frame_id: ''
voltage: 12.061639785766602
temperature: 0.0
current: 16.57807731628418
charge: 4.003036975860596
capacity: 5.0
design_capacity: .nan
percentage: 80.06074523925781
power_supply_status: 2
power_supply_health: 0
power_supply_technology: 0
present: true
cell_voltage: []
cell_temperature: []
location: ''
serial_number: ''
---
```

Copter: add battery and sensors to iris

---

ardupilot_gz_bringup/config/iris_bridge.yaml
ardupilot_gz_bringup/launch/robots/iris.launch.py
ardupilot_gz_gazebo/worlds/iris_runway.sdf
ros2_gz_macos.repos

Update the launch script for the iris quadcopter example to use UDP transport.
- Use UDP transport as default (instead of serial with virtual ports).
- Update config file (remove leading `/` so ROS topics are not all in global namespace).
- Update dependencies to use ArduPilot versions of repos where available.
- https://github.com/ArduPilot/ardupilot/pull/23703

Copter: use udp transport in launch

---

README.md
ros2_gz.repos
ros2_gz_macos.repos

The `ros2` branch of `ros_gz` now depends on `iron`.

Tools: update ros_gz dependency to use humble branch

---

.pre-commit-config.yaml
README.md
ardupilot_gz_application/.flake8
ardupilot_gz_application/package.xml
ardupilot_gz_bringup/.flake8
ardupilot_gz_bringup/package.xml
ardupilot_gz_description/.flake8
ardupilot_gz_description/hooks/ardupilot_gz_description.sh.in
ardupilot_gz_description/models/iris_with_lidar/model.config
ardupilot_gz_description/models/iris_with_lidar/model.sdf
ardupilot_gz_description/package.xml
ardupilot_gz_gazebo/.flake8
ardupilot_gz_gazebo/package.xml
ardupilot_gz_gazebo/worlds/iris_maze.sdf

Added pre-commit .yaml file with `black` and `xmllint` as well as some `pre-commit` hooks.
The pre-commit documentation recommends running this the first time to ensure that all the files in the repository are formatted correctly:
```bash
pre-commit run --all-files
```
So I will add a second commit to make the recommended changes

Tools: Add pre-commit with black and xmllint

---

ardupilot_gz_description/models/iris_with_lidar/model.sdf

A simple change to get the lidar on top of the iris instead of beneath it.
Before:
After:
This stops the lidar data from detecting the Copter's landing gear, which was causing problems with `nav2`'s obstacle avoidance features. The costmap without it is now clean:

Copter: get lidar above iris

---

ardupilot_gz_bringup/config/iris_bridge.yaml
ardupilot_gz_bringup/config/iris_lidar_bridge.yaml
ardupilot_gz_bringup/launch/robots/iris.launch.py
ardupilot_gz_bringup/launch/robots/iris_lidar.launch.py

The point of this PR is to eliminate some of the remappings necessary to work with this package, as discussed with @Ryanf55.
`/tf` and `/tf_static` should receive a `ros rep 105` compliant tf tree, in this case, the one coming from `robot_state_publisher`. 
Gazebo's tf tree can be renamed through the `ros_gz` yaml files instead of using another remap.
`/laser/scan` was renamed to `/scan` as this is used by both `cartographer` and `nav2`
https://github.com/ArduPilot/ardupilot_ros/pull/14
https://github.com/ArduPilot/ardupilot/pull/24819

Copter: default topic names

---

ardupilot_gz_bringup/package.xml

This allows `--packages-up-to` to be used correctly be declaring depenedencies. Also, it supports `rosdep` adding dependencies when we get to releasing binaries.
Tested with `rosdep`, no new errors introduced:
```
ryan@B650-970:~/Dev/ardu_ws$ rosdep install --from-paths src --ignore-src 
ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
ros_gz_bridge: Cannot locate rosdep definition for [gz-transport12]
ardupilot_gazebo: Cannot locate rosdep definition for [libgz-sim7-dev]
ros_gz_sim: Cannot locate rosdep definition for [gz-math7]
ros_gz_image: Cannot locate rosdep definition for [gz-transport12]
sdformat_urdf: Cannot locate rosdep definition for [sdformat13]
```
Now, it builds the packages you need for bringup.
``` …
```

Add missing exec dependencies

---

ardupilot_gz_bringup/launch/robots/iris.launch.py
ardupilot_gz_bringup/launch/robots/iris_lidar.launch.py
ardupilot_gz_bringup/package.xml
ardupilot_gz_bringup/rviz/iris.rviz
ardupilot_gz_bringup/rviz/iris_with_lidar.rviz
ardupilot_gz_description/models/iris_with_lidar/model.sdf
ardupilot_gz_gazebo/worlds/iris_maze.sdf

Fix the odometry transform for both copter examples.
- Closes #30
- https://github.com/ArduPilot/ardupilot_gazebo/pull/64
As reported in #30, rviz is reporting an invalid TF error when running the examples from the README page. The issue applies to both the `iris_runway.launch.py` and `iris_maze.launch.py` examples.
The reasons are explained in: https://github.com/ArduPilot/ardupilot_gz/issues/30#issuecomment-1721549208. In brief the change to use the `robot_state_publisher` as the authority for TF and remove the TF prefix means that the transform from `odom` to `base_link` provided by the Gazebo `OdometryPublisher` is no longer published to the topic `/tf`.
The following changes fix the issue:
- Change the frame names used in the copter model plugin XML for `OdometryPublisher`.  
- Add a …

Copter: fix odometry transform 

---

README.md
ardupilot_gz_bringup/config/wildthumper_bridge.yaml
ardupilot_gz_bringup/launch/robots/wildthumper.launch.py
ardupilot_gz_bringup/launch/wildthumper_playpen.launch.py
ardupilot_gz_bringup/package.xml
ardupilot_gz_bringup/rviz/wildthumper.rviz

Add launch files and configuration for a skid steer rover. 
- Rover is a skid-steer Wild Thumper.
- Use playpen world containing various obstacles.
- Requires model repository `SITL_Models` enabled as a `colcon` package called `ardupilot_sitl_models`.
- https://github.com/ArduPilot/SITL_Models/pull/100
- https://github.com/ArduPilot/SITL_Models/pull/101
- https://github.com/ArduPilot/ardupilot/pull/25204
```bash
$ cd ros2_ws/src
$ git clone https://github.com/ArduPilot/SITL_Models.git
$ cd ros2_ws/src
$ colcon build --packages-up-to ardupilot_gz_bringup
```
```bash
$ ros2 launch ardupilot_gz_bringup wildthumper_playpen.launch.py rviz:=true use_gz_tf:=true
```
Figure: rover in playpen world
Figure: rover model, TF and odometry in rviz 
```bash
[micro_ros_agent-3] 2023-10-06 19:14:53.766 …
```

Rover: add rover example

---

ardupilot_gz_bringup/config/wildthumper_bridge.yaml
ardupilot_gz_bringup/launch/robots/wildthumper.launch.py
ardupilot_gz_bringup/launch/wildthumper_playpen.launch.py
ardupilot_gz_bringup/rviz/wildthumper.rviz
ardupilot_gz_gazebo/worlds/wildthumper_playpen.sdf
ros2_gz.repos
ros2_gz_macos.repos

This is a follow up to https://github.com/ArduPilot/ardupilot_gz/pull/33 that adds a lidar to the rover model. It enables the rover model to be used with the cartographer and navigation launch configurations developed by @pedro-fuoco as part of his 2023 GSoC project. 
- https://github.com/ArduPilot/ardupilot_gz/pull/33
- https://github.com/ArduPilot/SITL_Models/pull/101
- https://github.com/ArduPilot/ardupilot/pull/25204
For testing and further details see the descriptions in the above PRs.

Rover: add lidar to rover example

---

ardupilot_gz_bringup/package.xml

`ardupilot_gazebo` is used in `src/ardupilot_gz/ardupilot_gz_bringup/launch/robots/iris.launch.py` but is missing from the `package.xml`
`ros_gz_bridge` is used in `src/ardupilot_gz/ardupilot_gz_bringup/launch/robots/iris_lidar.launch.py` but is missing from the `package.xml`
This work was sponsored by AeroVironment.

Add missing runtime dependency on ardupilot_gazebo and ros_gz_bridge

---

ardupilot_gz_gazebo/CMakeLists.txt
ardupilot_gz_gazebo/package.xml

Add support for Gazebo Harmonic retaining the default support for Gazebo Garden. The version used is controlled by the environment variable GZ_VERSION which should be either garden or harmonic. If not set the default is to assume garden.
- https://github.com/ArduPilot/ardupilot_gazebo/pull/66
- https://github.com/ros/sdformat_urdf/pull/23

Tools: support Gazebo Harmonic and Garden

---

ardupilot_gz_description/models/iris_with_lidar/model.sdf
ardupilot_gz_gazebo/worlds/iris_maze.sdf
ardupilot_gz_gazebo/worlds/iris_runway.sdf

Update pose following:
- https://github.com/ArduPilot/ardupilot_gazebo/pull/68
Ensure `<cma>` element is set to zero in LiftDrag plugin following:
- https://github.com/gazebosim/gz-sim/pull/2189
- Make runway orientation consistent with example in [ardupilot_gazebo](https://github.com/ArduPilot/ardupilot_gazebo).

Copter: update pose and lift plugin

---

ardupilot_gz_description/models/iris_with_lidar/model.sdf

Replace unsupported sdf elements in the `iris_with_lidar` model.
- `ignition` frame elements are deprecated in Harmonic.
- `<min_angle>` and `<max_angle>` do not have an attribute `degrees`.

Copter: replace unsupported sdf elements

---

README.md
ardupilot_gz_bringup/package.xml
ardupilot_gz_gazebo/CMakeLists.txt
ardupilot_gz_gazebo/package.xml

* Make default gazebo version `harmonic`
* Clean up instructions
* rosdep now resolves correctly

Default to harmonic

---

ardupilot_gz_bringup/launch/robots/iris.launch.py
ardupilot_gz_bringup/launch/robots/iris_lidar.launch.py
ardupilot_gz_bringup/launch/robots/wildthumper.launch.py

Remove the `ref:=...` argument from launch files. With https://github.com/ArduPilot/ardupilot/pull/27145 AP_DDS uses the micro-xrce-dds binary interface to create entities and the agent does not require a reference file to initialise the connection correctly.
- https://github.com/ArduPilot/ardupilot/pull/27145

Remove micro_ros_agent launch argument referencing dds_xrce_profile.xml

---

ardupilot_gz_bringup/config/iris_bridge.yaml

Change the Iris model to use the 3DoF gimbal.
- https://github.com/ArduPilot/ardupilot_gazebo/pull/124
Launch simulation
```bash
ros2 launch ardupilot_gz_bringup iris_runway.launch.py console:=True
```
and start a mavproxy interactive session to control:
```bash
mavproxy.py --master :14550
STABILIZE> mode guided
GUIDED> arm throttle
GUIDED> takeoff 2
GUIDED> Take Off started
GUIDED> rc 3 1500
GUIDED> circle
```
- The model appears correctly in Gazebo.
- The model appears correctly in rviz.
- The 3DoF gimbal links are visible in rviz2.
- The camera topic is relayed from Gazebo to ROS 2.

Copter: use 3DoF gimbal

---

README.md
ardupilot_gz_gazebo/CMakeLists.txt
ardupilot_gz_gazebo/package.xml

Add build option for Gazebo Ionic. The ROS 2 distros are moving to a new approach using `vendored` packages that do not explicitly state the version number, however I have not managed to get this working for macOS

Gazebo: support Gazebo Ionic
